### ISSUE TITLE
Web interface for cluster management

### ISSUE THREAD

**Issue by goncalo-pereira** [0blivi0n/oblivion-admin#1]
* Add node do cluster
* Remove node from cluster

**Comment by goncalo-pereira** [comment]
* Add node do cluster
* Remove node from cluster

**Comment by goncalo-pereira** [comment]
![cluster_home](https://cloud.githubusercontent.com/assets/3442235/6348759/f344865c-bc1a-11e4-884b-a76041a378f7.png)

**Comment by jjmrocha** [comment]
Remove button is only available when the node is offline
